#!/usr/bin/env python3
import os
import sys

import fontforge

out = os.environ["out"]
for f in sys.stdin.read().split():
    print(f"/{fontforge.open(f).fontname} ({os.path.join(out, 'share', f)}) ;")
